allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  blake-hash: false
  bufferutil: false
  esbuild: true
  msw: false
  protobufjs: false
  secp256k1: false
  sharp: false
  tiny-secp256k1: false
  unrs-resolver: false
  usb: false
  utf-8-validate: false
  sodium-native: false
