/// Projects the virtual yield generated by a locked plan over time.
///
/// Uses simple interest formula:
///   accrued = principal * (rate_bps / 10000) * (elapsed_secs / seconds_per_year)
///
/// The yield_rate_bps is in basis points (e.g., 500 = 5% APY).
pub fn calculate_yield(amount: f64, yield_rate_bps: u32, elapsed_secs: u64) -> f64 {
    if yield_rate_bps == 0 || elapsed_secs == 0 {
        return 0.0;
    }

    let rate = yield_rate_bps as f64 / 10_000.0;
    let seconds_per_year = 365.25 * 24.0 * 3600.0;
    let time_years = elapsed_secs as f64 / seconds_per_year;

    amount * rate * time_years
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_zero_yield_rate() {
        assert_eq!(calculate_yield(1000.0, 0, 86400), 0.0);
    }

    #[test]
    fn test_zero_elapsed() {
        assert_eq!(calculate_yield(1000.0, 500, 0), 0.0);
    }

    #[test]
    fn test_one_year_at_5_percent() {
        // 5% APY = 500 bps, 1 year = 31,536,000 seconds (approx)
        let one_year_secs = (365.25 * 24.0 * 3600.0) as u64;
        let yield_amount = calculate_yield(1000.0, 500, one_year_secs);
        // Should be ~50.0 (5% of 1000)
        assert!((yield_amount - 50.0).abs() < 0.01);
    }

    #[test]
    fn test_half_year() {
        // 10% APY = 1000 bps, half year should yield ~5% of principal
        let half_year_secs = (365.25 * 24.0 * 3600.0 / 2.0) as u64;
        let yield_amount = calculate_yield(1000.0, 1000, half_year_secs);
        // Should be ~50.0 (10% of 1000 for half year)
        assert!((yield_amount - 50.0).abs() < 0.01);
    }

    #[test]
    fn test_large_amount() {
        let one_year_secs = (365.25 * 24.0 * 3600.0) as u64;
        let yield_amount = calculate_yield(1_000_000.0, 200, one_year_secs);
        // 2% of 1,000,000 = 20,000
        assert!(
            (yield_amount - 20_000.0).abs() < 1.0,
            "Unexpected yield_amount = {:.6}; expected ≈ 20000.0",
            yield_amount
        );
    }
}
